project:
  output-dir: _output
  
author: 
 -  name: "Hugo Roussaffa"
    email: hugoroussaffa@gmail.com
    Tel: +687 97.83.24
    Position: "Expert Géomatique – Architecte data - Consultant"
    affiliation: 
      name: Yapuka SARL
      address: "BP 38, 98836 Dumbéa Mairie, Nouvelle-Calédonie"
      Ridet : 1 568 070.001
date: today
date-format: long
number-sections: true

crossref:
  sec-prefix: "Chapitre "

logo: "ressources/OEIL_logo.png" #logo de l'oeil
image_font_1: "ressources/MJunckerOEIL.jpg" #image de fond numéro 1
image_font_2:  "ressources/eau-monitoring.png"  #image 2 supérieure
logo_partenaire: "ressources/logo_yapuka.png" #logo partenaire
filters:
  - filters/todo.lua

lang: fr
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    code-fold: true
    embed-resources: true
    theme: lumen
    css: ressources/pricing.css
  pdf:
    pdf-engine: xelatex
    df-print: kable # Formate les dataframes pandas proprement en LaTeX
    header-includes:
      - \usepackage{soul}
      - \sethlcolor{yellow}
      - \usepackage{pdfpages}
    toc: true
    colorlinks: true
    toc-depth: 3
    fig-width: 8
    fig-height: 6
    fig-pos: 'H'
    number-sections: true
    keep_tex: false
    include-in-header: 
      - "in-header.tex"
    fontsize: 11pt
    mainfont: Calibri
    template-partials: 
      - "before-body.tex"
  eisvogel-pdf:
    pdf-engine: xelatex
    header-includes:
      - \usepackage{soul}
      - \sethlcolor{yellow}
    titlepage: true
    titlepage-logo: logo_yapuka.png
    toc: true
    toc-title: "Sommaire"
    number-sections: true
    include-in-header: header.tex
    callout-icon: false
    callout-appearance: simple
  docx:
    reference-doc: custom-reference.docx
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github