# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Ollama local
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: qwen2.5-coder 7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - apply
      - autocomplete
      - chat
      - edit