FROM node:20-alpine

WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm ci --omit=dev

# Copy source
COPY server.js .
COPY public ./public

ENV PORT=8080
EXPOSE 8080

CMD ["node", "server.js"]