---
title: "Géologie"
subtitle: "Indicateur n⁰24"
categories: ["Vulnérabilité", "Vulnérabilité"]
---

Type de sol et de roche. Propriété des sols correspondant (infiltrant / intermédiaire / ruisselant)

## Identification

| Champ               | Valeur |
|---------------------|--------|
| **Identifiant**     | `24` |
| **Famille**         | Vulnérabilité |
| **Type d'indicateur**            | Vulnérabilité |
| **Unité de mesure**           | % |
| **Support spatial du calcul** | maille |
| **Fréquence de mise à jour**       | Fixe |

## Objectif

Comparer les bassins versants selon les propriétés des sols afin de qualifier leur comportement hydrologique.

## Description


## Sources de données

Géorep – DIMENC  https://georep.nc (explorateur géosciences)

## Méthode de calcul



## Modalités de calcul

Regroupement des classes géologiques en catégories simplifiées.

## Contraintes / limites

Risque de redondance avec d’autres indicateurs et nécessité de simplification.

## Modalités de calcul

Regroupement des classes géologiques en catégories simplifiées.

## Modalité de calcul

Regroupement des classes géologiques en catégories simplifiées.

