---
title: "Pluviométrie"
subtitle: "Indicateur n⁰28"
categories: ["Pression quanti", "Pression"]
---

Quantité de pluie reçue.

## Identification

| Champ               | Valeur |
|---------------------|--------|
| **Identifiant**     | `28` |
| **Famille**         | Pression quanti |
| **Type d'indicateur**            | Pression |
| **Unité de mesure**           | mm |
| **Support spatial du calcul** | maille |
| **Fréquence de mise à jour**       | Annuelle |

## Objectif

Comparer les bassins versants selon les apports en eau afin de contextualiser la disponibilité de la ressource.

## Description


## Sources de données

Géorep – Portail Météorologie et Climat  https://georep.nc (Environnement → climat)

## Méthode de calcul



## Modalités de calcul

Calcul de la moyenne spatiale par bassin versant.

## Contraintes / limites

Redondance avec d’autres indicateurs de disponibilité de la ressource.

## Modalités de calcul

Calcul de la moyenne spatiale par bassin versant.

## Modalité de calcul

Calcul de la moyenne spatiale par bassin versant.

