---
title: "Capacité réservoir"
subtitle: "Indicateur n⁰3"
categories: ["AEP", "Enjeu"]
---

Quantité d’eau pouvant être stockée pour faire face aux besoins.

## Identification

| Champ               | Valeur |
|---------------------|--------|
| **Identifiant**     | `3` |
| **Famille**         | AEP |
| **Type d'indicateur**            | Enjeu |
| **Unité de mesure**           | m3 |
| **Support spatial du calcul** | UD |
| **Fréquence de mise à jour**       | Annuelle |

## Objectif

Comparer la capacité de stockage associée aux captages afin d’identifier les systèmes les plus résilients face aux aléas.

## Description


## Sources de données

DASS (étude zones isolées – base existante non relationnelle)

## Méthode de calcul



## Modalités de calcul

Somme des volumes par unité de distribution, puis rattachement au captage.

## Contraintes / limites

Données non liées entre captage et unité de distribution, nécessitant un travail de modélisation des relations.

## Modalités de calcul

Somme des volumes par unité de distribution, puis rattachement au captage.

## Modalité de calcul

Somme des volumes par unité de distribution, puis rattachement au captage.

