---
title: "Traitement"
subtitle: "Indicateur n⁰4"
categories: ["AEP", "Enjeu"]
---

Type de traitement appliqué à l’eau avant distribution.

## Identification

| Champ               | Valeur |
|---------------------|--------|
| **Identifiant**     | `4` |
| **Famille**         | AEP |
| **Type d'indicateur**            | Enjeu |
| **Unité de mesure**           | Classe (pas de traitement / traitement partiel / traitement complet) |
| **Support spatial du calcul** | UD |
| **Fréquence de mise à jour**       | Annuelle |

## Objectif

Comparer le niveau de sécurisation sanitaire des captages afin d’identifier ceux présentant des risques pour l’alimentation en eau potable.

## Description


## Sources de données

DASS (étude zones isolées)

## Méthode de calcul



## Modalités de calcul

Attribution d’une classe standardisée par unité de distribution, puis association au captage.

## Contraintes / limites

Hétérogénéité des informations disponibles, nécessitant une standardisation des classes de traitement.

## Modalités de calcul

Attribution d’une classe standardisée par unité de distribution, puis association au captage.

## Modalité de calcul

Attribution d’une classe standardisée par unité de distribution, puis association au captage.

